metadata:
  #  Must match the 'spring.application.name' property of the application
  name: ${project.artifactId}
data:
  application.properties: |
    # spring application properties file
    spring.application.name=eiffel-intelligence-frontend-artifact
    ei.frontendServiceHost=${project.artifactId}.iris.seli.gic.ericsson.se
    ei.frontendServicePort=8080
    ei.backendServerHost=eiffel-intelligence-artifact-wrapper
    ei.backendServerPort=8090