metadata:
  #  Must match the 'spring.application.name' property of the application
  name: ${project.artifactId}
data:
  application.properties: |
    # spring application properties file
    spring.application.name=${project.artifactId}
    logging.level.root=INFO
    logging.level.org.springframework.web=DEBUG
    logging.level.com.ericsson.ei=DEBUG
    ei.frontendServiceHost=${project.artifactId}.iris.seli.gic.ericsson.se
    ei.frontendServicePort=80
    ei.frontendContextPath=
    ei.useSecureHttpFrontend=false
    #ei.backendServerHost=eiffel-intelligence-artifact-wrapper.iris.seli.gic.ericsson.se
    #ei.backendServerPort=80
    ei.backendServerHost=eiffel-intelligence-artifact-wrapper
    ei.backendServerPort=8090
    ei.backendContextPath=
    ei.useSecureHttpBackend=false
    ei.backendInstancesPath=