apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ${project.artifactId}
spec:
  rules:
  - host: ${project.artifactId}.${deployment.host.ingress}
    http:
      paths:
      - backend:
          serviceName: ${project.artifactId}
          servicePort: 8080
        path: /